create table mid2008.households(
hhid character varying,
sourceid text,
hh_gew numeric,
h01 text,
h02 numeric,
p1nr numeric,
p2nr numeric,
p3nr numeric,
p4nr numeric,
p5nr numeric,
p6nr numeric,
p7nr numeric,
p8nr numeric,
hpalter1 numeric,
hpalter2 numeric,
hpalter3 numeric,
hpalter4 numeric,
hpalter5 numeric,
hpalter6 numeric,
hpalter7 numeric,
hpalter8 numeric,
hp_sex1 text,
hp_sex2 text,
hp_sex3 text,
hp_sex4 text,
hp_sex5 text,
hp_sex6 text,
hp_sex7 text,
hp_sex8 text,
hp_beru1 text,
hp_beru2 text,
hp_beru3 text,
hp_beru4 text,
hp_beru5 text,
hp_beru6 text,
hp_beru7 text,
hp_beru8 text,
hp_bkat1 text,
hp_bkat2 text,
hp_bkat3 text,
hp_bkat4 text,
hp_bkat5 text,
hp_bkat6 text,
hp_bkat7 text,
hp_bkat8 text,
hp_taet1 text,
hp_taet2 text,
hp_taet3 text,
hp_taet4 text,
hp_taet5 text,
hp_taet6 text,
hp_taet7 text,
hp_taet8 text,
hpbesch1 text,
hpbesch2 text,
hpbesch3 text,
hpbesch4 text,
hpbesch5 text,
hpbesch6 text,
hpbesch7 text,
hpbesch8 text,
hpkwfs1 text,
hpkwfs2 text,
hpkwfs3 text,
hpkwfs4 text,
hpkwfs5 text,
hpkwfs6 text,
hpkwfs7 text,
hpkwfs8 text,
h04_1 numeric,
h04_2 numeric,
h04_3 numeric,
h040_1 text,
h040_2 text,
h040_3 text,
h040_4 text,
h040_5 text,
h040_6 text,
h040_7 text,
h040_8 text,
grkpkw text,
hheink text,
oek_stat text,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp text,
klasse_h text,
status_h text,
fahrlj_h numeric,
co2tag_h numeric,
bland text,
westost text,
polgk text,
rtyp text,
rtypd7 text,
ktyp text,
ktyp_zsg text,
sgtyp text,
sgtypd text,
psu_nr numeric
);

copy mid2008.households from '/home/dhosse/Haushalte_l.csv' delimiter ';'

create view view_mid2008_households as
select
hhid as "Haushalts-ID",
sourceid as "Interview-Methode",
hh_gew as "Gewichtungsfaktor Haushalte",
h01 as "Leben Sie in Ihrem Haushalt...",
h02 as "Anzahl Personen im Haushalt",
p1nr as "Person 1",
p2nr as "Person 2",
p3nr as "Person 3",
p4nr as "Person 4",
p5nr as "Person 5",
p6nr as "Person 6",
p7nr as "Person 7",
p8nr as "Person 8",
hpalter1 as "Person 1 Alter",
hpalter2 as "Person 2 Alter",
hpalter3 as "Person 3 Alter",
hpalter4 as "Person 4 Alter",
hpalter5 as "Person 5 Alter",
hpalter6 as "Person 6 Alter",
hpalter7 as "Person 7 Alter",
hpalter8 as "Person 8 Alter",
hp_sex1 as "Person 1 Geschlecht",
hp_sex2 as "Person 2 Geschlecht",
hp_sex3 as "Person 3 Geschlecht",
hp_sex4 as "Person 4 Geschlecht",
hp_sex5 as "Person 5 Geschlecht",
hp_sex6 as "Person 6 Geschlecht",
hp_sex7 as "Person 7 Geschlecht",
hp_sex8 as "Person 8 Geschlecht",
hp_beru1 as "Person 1 berufstätig",
hp_beru2 as "Person 2 berufstätig",
hp_beru3 as "Person 3 berufstätig",
hp_beru4 as "Person 4 berufstätig",
hp_beru5 as "Person 5 berufstätig",
hp_beru6 as "Person 6 berufstätig",
hp_beru7 as "Person 7 berufstätig",
hp_beru8 as "Person 8 berufstätig",
hp_bkat1 as "Person 1 Arbeitszeit",
hp_bkat2 as "Person 2 Arbeitszeit",
hp_bkat3 as "Person 3 Arbeitszeit",
hp_bkat4 as "Person 4 Arbeitszeit",
hp_bkat5 as "Person 5 Arbeitszeit",
hp_bkat6 as "Person 6 Arbeitszeit",
hp_bkat7 as "Person 7 Arbeitszeit",
hp_bkat8 as "Person 8 Arbeitszeit",
hp_taet1 as "Person 1 Tätigkeit",
hp_taet2 as "Person 2 Tätigkeit",
hp_taet3 as "Person 3 Tätigkeit",
hp_taet4 as "Person 4 Tätigkeit",
hp_taet5 as "Person 5 Tätigkeit",
hp_taet6 as "Person 6 Tätigkeit",
hp_taet7 as "Person 7 Tätigkeit",
hp_taet8 as "Person 8 Tätigkeit",
hpbesch1 as "Person 1 Tätigkeit und Arbeitszeit",
hpbesch2 as "Person 2 Tätigkeit und Arbeitszeit",
hpbesch3 as "Person 3 Tätigkeit und Arbeitszeit",
hpbesch4 as "Person 4 Tätigkeit und Arbeitszeit",
hpbesch5 as "Person 5 Tätigkeit und Arbeitszeit",
hpbesch6 as "Person 6 Tätigkeit und Arbeitszeit",
hpbesch7 as "Person 7 Tätigkeit und Arbeitszeit",
hpbesch8 as "Person 8 Tätigkeit und Arbeitszeit",
hpkwfs1 as "Person 1 Pkw-Führerschein",
hpkwfs2 as "Person 2 Pkw-Führerschein",
hpkwfs3 as "Person 3 Pkw-Führerschein",
hpkwfs4 as "Person 4 Pkw-Führerschein",
hpkwfs5 as "Person 5 Pkw-Führerschein",
hpkwfs6 as "Person 6 Pkw-Führerschein",
hpkwfs7 as "Person 7 Pkw-Führerschein",
hpkwfs8 as "Person 8 Pkw-Führerschein",
h04_1 as "Anzahl Fahrräder",
h04_2 as "Anzahl Motorräder, Mopeds, Mofas",
h04_3 as "Anzahl Autos",
h040_1 as "kein Auto weil nicht nötig",
h040_2 as "bewusster Verzicht auf ein Auto",
h040_3 as "Auto ist zu teuer",
h040_4 as "kein Auto aus gesundheitlichen Gründen",
h040_5 as "kein Auto aus Altersgründen",
h040_6 as "kein Auto aus anderen Gründen",
h040_7 as "Aussage zu Nicht-Pkw-Besitz verweigert",
h040_8 as "weiß nicht",
grkpkw as "Hauptgrund für Nicht-Pkw-Besitz",
hheink as "Haushaltseinkommen [€/Monat]",
oek_stat as "ökonomischer Status",
hhgr06 as "Person unter 6 Jahren",
hhgr14 as "Personen unter 14 Jahren",
hhgr18 as "Personen unter 18 Jahren",
anzerw as "Personen über 18 Jahre",
hhtyp as "Haushaltstyp",
klasse_h as "höchste Auto-Typklasse",
status_h as "höchster Auto-Status",
fahrlj_h as "Fahrleistung [km/Jahr]",
co2tag_h as "CO2-Emissionen [kg/Stichtag]",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeindegrößenklasse",
rtyp as "BBSR Regionsgrundtyp",
rtypd7 as "BBSR differenzierter Regionstyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBR zusammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.households;
