create table mid2008.cars(
hhid character varying,
vmid character varying,
sourceid character varying,
a_gew numeric,
h041 character varying,
h042 character varying,
h044 character varying,
h046 character varying,
h048 character varying,
ps numeric,
kW numeric,
h0411 character varying,
h0416 character varying,
h0412 numeric,
h0413 numeric,
h0414 numeric,
fahrlj numeric,
klasse character varying,
status character varying,
seg_kba character varying,
anzfahrt numeric,
gesfkm numeric,
durchkm numeric,
gesfmin numeric,
durchmin numeric,
anzfpers numeric,
besgrad numeric,
stich_j numeric,
stich_m character varying,
stichtag character varying,
stichwo numeric,
sex_hn character varying,
alter_hn numeric,
besch_hn character varying,
hheink character varying,
oek_stat character varying,
h02 numeric,
h04_3 numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp character varying,
bland character varying,
westost character varying,
polgk character varying,
rtyp character varying,
rtypd7 character varying,
ktyp character varying,
ktyp_zsg character varying,
sgtyp character varying,
sgtypd character varying,
psu_nr numeric
)

copy mid2008.cars from '/home/dhosse/Autos_l.csv' delimiter ';'

create view view_mid2008_cars as
select
hhid as "Haushalts-ID",
vmid as "Fahrzeug-ID",
sourceid as "Interview-Methode",
a_gew as "Gewichtungsfaktor Autos",
h041 as "Hersteller",
h042 as "Modellbezeichnung",
h044 as "Hauptnutzer (Personen-ID)",
h046 as "Zulassungsart",
h048 as "Antriebstechnologie",
ps as "PS",
kW as "kW",
h0411 as "Üblicher Stellplatz",
h0416 as "Stellplatzsuche",
h0412 as "Baujahr",
h0413 as "Anschaffungsjahr",
h0414 as "aktueller Kilometerstand",
fahrlj as "Fahrleistung [km/Jahr]",
klasse as "Typklasse (nach Hersteller und Leistung)",
status as "Statusklasse (nach Typklasse und Baujahr)",
seg_kba as "PKW-Segmenteinteilung nach KBA",
anzfahrt as "Fahrten am Stichtag",
gesfkm as "Gesamtstrecke am Stichtag [km]",
durchkm as "durchschnittliche Entfernung der Fahrten am Stichtag [km]",
gesfmin as "Gesamtfahrzeit am Stichtag [min]",
durchmin as "durchschnittliche Fahrdauer am Stichtag [min]",
anzfpers as "Anzahl beförderter Personen am Stichtag",
besgrad as "durchschnittlicher Besetzungsgrad am Stichtag",
stich_j as "Stichtag (Kalenderjahr)",
stich_m as "Stichtag (Kalendermonat)",
stichtag as "Stichtag (Wochentag)",
stichwo as "Stichtag (Kalenderwoche)",
sex_hn as "Geschlecht Hauptnutzer",
alter_hn as "Alter Hauptnutzer",
besch_hn as "Beschäftigung Hauptnutzer",
hheink as "Haushaltseinkommen [€/Monat]",
oek_stat as "ökonomischer Status",
h02 as "Anzahl Personen im Haushalt",
h04_3 as "Anzahl Autos im Haushalt",
hhgr06 as "Personen unter 6 Jahren",
hhgr14 as "Personen unter 14 Jahren",
hhgr18 as "Personen unter 18 Jahren",
anzerw as "Personen über 18 Jahren",
hhtyp as "Haushaltstyp",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeinegröße",
rtyp as "BBSR-Regiongrundtyp",
rtypd7 as "BBSR differenzierter Regionsgrundtyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBSR zuammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.cars;

create table mid2008.households(
hhid character varying,
sourceid character varying,
hh_gew numeric,
h01 character varying,
h02 numeric,
p1nr numeric,
p2nr numeric,
p3nr numeric,
p4nr numeric,
p5nr numeric,
p6nr numeric,
p7nr numeric,
p8nr numeric,
hpalter1 numeric,
hpalter2 numeric,
hpalter3 numeric,
hpalter4 numeric,
hpalter5 numeric,
hpalter6 numeric,
hpalter7 numeric,
hpalter8 numeric,
hp_sex1 character varying,
hp_sex2 character varying,
hp_sex3 character varying,
hp_sex4 character varying,
hp_sex5 character varying,
hp_sex6 character varying,
hp_sex7 character varying,
hp_sex8 character varying,
hp_beru1 character varying,
hp_beru2 character varying,
hp_beru3 character varying,
hp_beru4 character varying,
hp_beru5 character varying,
hp_beru6 character varying,
hp_beru7 character varying,
hp_beru8 character varying,
hp_bkat1 character varying,
hp_bkat2 character varying,
hp_bkat3 character varying,
hp_bkat4 character varying,
hp_bkat5 character varying,
hp_bkat6 character varying,
hp_bkat7 character varying,
hp_bkat8 character varying,
hp_taet1 character varying,
hp_taet2 character varying,
hp_taet3 character varying,
hp_taet4 character varying,
hp_taet5 character varying,
hp_taet6 character varying,
hp_taet7 character varying,
hp_taet8 character varying,
hpbesch1 character varying,
hpbesch2 character varying,
hpbesch3 character varying,
hpbesch4 character varying,
hpbesch5 character varying,
hpbesch6 character varying,
hpbesch7 character varying,
hpbesch8 character varying,
hpkwfs1 character varying,
hpkwfs2 character varying,
hpkwfs3 character varying,
hpkwfs4 character varying,
hpkwfs5 character varying,
hpkwfs6 character varying,
hpkwfs7 character varying,
hpkwfs8 character varying,
h04_1 numeric,
h04_2 numeric,
h04_3 numeric,
h040_1 character varying,
h040_2 character varying,
h040_3 character varying,
h040_4 character varying,
h040_5 character varying,
h040_6 character varying,
h040_7 character varying,
h040_8 character varying,
grkpkw character varying,
hheink character varying,
oek_stat character varying,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp character varying,
klasse_h character varying,
status_h character varying,
fahrlj_h numeric,
co2tag_h numeric,
bland character varying,
westost character varying,
polgk character varying,
rtyp character varying,
rtypd7 character varying,
ktyp character varying,
ktyp_zsg character varying,
sgtyp character varying,
sgtypd character varying,
psu_nr numeric
);

copy mid2008.households from '/home/dhosse/Haushalte_l.csv' delimiter ';'

create view view_mid2008_households as
select
hhid as "Haushalts-ID",
sourceid as "Interview-Methode",
hh_gew as "Gewichtungsfaktor Haushalte",
h01 as "Leben Sie in Ihrem Haushalt...",
h02 as "Anzahl Personen im Haushalt",
p1nr as "Person 1",
p2nr as "Person 2",
p3nr as "Person 3",
p4nr as "Person 4",
p5nr as "Person 5",
p6nr as "Person 6",
p7nr as "Person 7",
p8nr as "Person 8",
hpalter1 as "Person 1 Alter",
hpalter2 as "Person 2 Alter",
hpalter3 as "Person 3 Alter",
hpalter4 as "Person 4 Alter",
hpalter5 as "Person 5 Alter",
hpalter6 as "Person 6 Alter",
hpalter7 as "Person 7 Alter",
hpalter8 as "Person 8 Alter",
hp_sex1 as "Person 1 Geschlecht",
hp_sex2 as "Person 2 Geschlecht",
hp_sex3 as "Person 3 Geschlecht",
hp_sex4 as "Person 4 Geschlecht",
hp_sex5 as "Person 5 Geschlecht",
hp_sex6 as "Person 6 Geschlecht",
hp_sex7 as "Person 7 Geschlecht",
hp_sex8 as "Person 8 Geschlecht",
hp_beru1 as "Person 1 berufstätig",
hp_beru2 as "Person 2 berufstätig",
hp_beru3 as "Person 3 berufstätig",
hp_beru4 as "Person 4 berufstätig",
hp_beru5 as "Person 5 berufstätig",
hp_beru6 as "Person 6 berufstätig",
hp_beru7 as "Person 7 berufstätig",
hp_beru8 as "Person 8 berufstätig",
hp_bkat1 as "Person 1 Arbeitszeit",
hp_bkat2 as "Person 2 Arbeitszeit",
hp_bkat3 as "Person 3 Arbeitszeit",
hp_bkat4 as "Person 4 Arbeitszeit",
hp_bkat5 as "Person 5 Arbeitszeit",
hp_bkat6 as "Person 6 Arbeitszeit",
hp_bkat7 as "Person 7 Arbeitszeit",
hp_bkat8 as "Person 8 Arbeitszeit",
hp_taet1 as "Person 1 Tätigkeit",
hp_taet2 as "Person 2 Tätigkeit",
hp_taet3 as "Person 3 Tätigkeit",
hp_taet4 as "Person 4 Tätigkeit",
hp_taet5 as "Person 5 Tätigkeit",
hp_taet6 as "Person 6 Tätigkeit",
hp_taet7 as "Person 7 Tätigkeit",
hp_taet8 as "Person 8 Tätigkeit",
hpbesch1 as "Person 1 Tätigkeit und Arbeitszeit",
hpbesch2 as "Person 2 Tätigkeit und Arbeitszeit",
hpbesch3 as "Person 3 Tätigkeit und Arbeitszeit",
hpbesch4 as "Person 4 Tätigkeit und Arbeitszeit",
hpbesch5 as "Person 5 Tätigkeit und Arbeitszeit",
hpbesch6 as "Person 6 Tätigkeit und Arbeitszeit",
hpbesch7 as "Person 7 Tätigkeit und Arbeitszeit",
hpbesch8 as "Person 8 Tätigkeit und Arbeitszeit",
hpkwfs1 as "Person 1 Pkw-Führerschein",
hpkwfs2 as "Person 2 Pkw-Führerschein",
hpkwfs3 as "Person 3 Pkw-Führerschein",
hpkwfs4 as "Person 4 Pkw-Führerschein",
hpkwfs5 as "Person 5 Pkw-Führerschein",
hpkwfs6 as "Person 6 Pkw-Führerschein",
hpkwfs7 as "Person 7 Pkw-Führerschein",
hpkwfs8 as "Person 8 Pkw-Führerschein",
h04_1 as "Anzahl Fahrräder",
h04_2 as "Anzahl Motorräder, Mopeds, Mofas",
h04_3 as "Anzahl Autos",
h040_1 as "kein Auto weil nicht nötig",
h040_2 as "bewusster Verzicht auf ein Auto",
h040_3 as "Auto ist zu teuer",
h040_4 as "kein Auto aus gesundheitlichen Gründen",
h040_5 as "kein Auto aus Altersgründen",
h040_6 as "kein Auto aus anderen Gründen",
h040_7 as "Aussage zu Nicht-Pkw-Besitz verweigert",
h040_8 as "weiß nicht",
grkpkw as "Hauptgrund für Nicht-Pkw-Besitz",
hheink as "Haushaltseinkommen [€/Monat]",
oek_stat as "ökonomischer Status",
hhgr06 as "Personen unter 6 Jahren",
hhgr14 as "Personen unter 14 Jahren",
hhgr18 as "Personen unter 18 Jahren",
anzerw as "Personen über 18 Jahren",
hhtyp as "Haushaltstyp",
klasse_h as "höchste Auto-Typklasse",
status_h as "höchster Auto-Status",
fahrlj_h as "Fahrleistung [km/Jahr]",
co2tag_h as "CO2-Emissionen [kg/Stichtag]",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeindegrößenklasse",
rtyp as "BBSR Regionsgrundtyp",
rtypd7 as "BBSR differenzierter Regionstyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBR zusammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.households;
