create table mop1994.households(
id character varying,
jahr numeric,
bik numeric,
raumtyp numeric,
bflr numeric,
region numeric,
kreis numeric,
gemeinde numeric,
plz numeric,
gkz numeric,
ewzahl numeric,
wetter numeric,
umzug numeric,
lage numeric,
hhtyp numeric,
hhgro numeric,
p0_10 numeric,
einko numeric,
pkwhh numeric,
pkwpriv1 numeric,
pkwpriv2 numeric,
pkwpriv3 numeric,
pkwnutz1 numeric,
pkwnutz2 numeric,
pkwnutz3 numeric,
parkstr1 numeric,
parkstr2 numeric,
parkstr3 numeric,
parkgar numeric,
parkprob numeric,
haltbus numeric,
haltbusz numeric,
haltstr numeric,
haltstrz numeric,
haltug numeric,
haltugz numeric,
oeffzuf numeric,
eink1 numeric,
eink1km numeric,
eink2 numeric,
eink2km numeric,
kneipe numeric,
kneipekm numeric,
kino numeric,
kinokm numeric,
sport numeric,
sportkm numeric,
zweitw numeric,
zweitwkm numeric,
carshar numeric,
handy numeric,
pc numeric,
pcweb numeric,
gewhhwo numeric
);

copy mop1994.households from '/home/dhosse/Dokumente/10_data/MoP/1994/Haushalte.csv' delimiter ';'
