create table mop1994.households(
id character varying,
jahr numeric,
bik numeric,
raumtyp numeric,
bflr numeric,
region numeric,
kreis numeric,
gemeinde numeric,
plz numeric,
gkz numeric,
ewzahl numeric,
wetter numeric,
umzug numeric,
lage numeric,
hhtyp numeric,
hhgro numeric,
p0_10 numeric,
einko numeric,
pkwhh numeric,
pkwpriv1 numeric,
pkwpriv2 numeric,
pkwpriv3 numeric,
pkwnutz1 numeric,
pkwnutz2 numeric,
pkwnutz3 numeric,
parkstr1 numeric,
parkstr2 numeric,
parkstr3 numeric,
parkgar numeric,
parkprob numeric,
haltbus numeric,
haltbusz numeric,
haltstr numeric,
haltstrz numeric,
haltu numeric,
haltuz numeric,
halts numeric,
haltsz numeric,
haltzug numeric,
haltzugz numeric,
oeffzuf numeric,
eink1 numeric,
eink1km numeric,
eink2 numeric,
eink2km numeric,
kneipe numeric,
kneipekm numeric,
kino numeric,
kinokm numeric,
sport numeric,
sportkm numeric,
zweitw numeric,
zweitwkm numeric,
carshar numeric,
handy numeric,
pc numeric,
pcweb numeric,
gewhhwo numeric
);

copy mop1994.households from '/home/dhosse/Dokumente/10_data/MoP/1994/Haushalte.csv' delimiter ';'

create view view_mop1994_households as select
id as "Haushalts-ID",
jahr as "Erhebungsjahr",
bik as "Raumtyp nach BIK",
raumtyp as "Raumtyp nach BIK (zusammengefasst)",
bflr as "BFLR",
region as "Regionstyp nach BFLR/BBR",
kreis as "Kreistyp nach BFLR/BBR",
gemeinde as "Gemeindetyp nach BFLR/BBR",
plz as "Postleitzahl",
gkz as "Gemeindekennzahl",
ewzahl as "politische Gemeindegrößenklasse",
wetter as "Zuordnung des HH-Standorts in den Wetterbereich der Wetterstationen",
umzug as "Umzug im vergangenen Jahr",
lage as "Lage der Wohnung des HH (Selbsteinschätzung)",
hhtyp as "Haushaltstyp",
hhgro as "Anzahl Personen",
p0_10 as "Anzahl Kinder",
einko as "monatliches Haushaltseinkommen",
pkwhh as "Anzahl Pkw",
pkwpriv1 as "Eigentumsverhältnis des Erstwagens",
pkwpriv2 as "Eigentumsverhältnis des Zweitwagens",
pkwpriv3 as "Eigentumsverhältnis des Drittwagens",
pkwnutz1 as "Nutzung des Erstwagens",
pkwnutz2 as "Nutzung des Zweitwagens",
pkwnutz3 as "Nutzung des Drittwagens",
parkstr1 as "Angabe des Parkplatzes des Erstwagens",
parkstr2 as "Angabe des Parkplatzes des Zweitwagens",
parkstr3 as "Angabe des Parkplatzes des Drittwagens",
parkgar as "Garage oder privater Parkplatz vorhanden",
parkprob as "Schwierigkeit, in der Nähe der Wohnung einen Parkplatz zu finden",
haltbus as "Bushaltestelle zu Fuß zu erreichen",
haltbusz as "Dauer des Fußwegs von Wohnung zur Bushaltestelle",
haltstr as "Straßenbahnhaltestelle zu Fuß zu erreichen",
haltstrz as "Dauer des Fußwegs von Wohnung zu Straßenbahnhaltestelle",
haltu as "U-Bahn-Haltestelle zu Fuß zu erreichen",
haltuz as "Dauer des Fußwegs von Wohnung zu U-Bahn-Haltestelle",
halts as "S-Bahn-Haltestelle zu Fuß zu erreichen",
haltsz as "Dauer des Fußwegs von Wohnung zu S-Bahn-Haltestelle",
haltzug as "Bahnhof zu Fuß zu erreichen",
haltzugz as "Dauer des Fußwegs von Wohnung zu Bahnhof",
oeffzuf as "Zufriedenheit mit ÖV-Anbindung",
eink1 as "Einkaufsmöglichkeit für täglichen Bedarf (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
eink1km as "Entfernung zur nächsten Einkaufsmöglichkeit für täglichen Bedarf [km]",
eink2 as "Einkaufsmöglichkeit (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
eink2km as "Entfernung zur nächsten Einkaufsmöglichkeit [km]",
kneipe as "Kneipe / Café (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
kneipekm as "Entfernung zur nächsten Kneipe / Café [km]",
kino as "Ausgehmöglichkeiten (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
kinokm as "Entfernung zur nächsten Ausgehmöglichkeit [km]",
sport as "Sportstätten (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
sportkm as "Entfernung zur nächsten Sportstätte [km]",
zweitw as "Zweitwohnsitz vorhanden",
zweitwkm as "Entfernung zum Zweitwohnsitz [km]",
carshar as "Carsharing-Mitglied im Haushalt",
handy as "Anzahl Handys im Haushalt",
pc as "PC im Haushalt",
pcweb as "Internetzugang",
gewhhwo as "Hochrechnenfaktor"
from mop1994.households;

create table mop1994.persons(
id character varying,
persnr character varying,
jahr numeric,
ausfueller numeric,
sex numeric,
gebjahr numeric,
alter numeric,
schulab numeric,
beruf numeric,
wechsarb numeric,
lagearb numeric,
oefferr numeric,
fussmin numeric,
parkp numeric,
fspkw numeric,
fsmot numeric,
pkwverf numeric,
zeitopnv numeric,
bahncard numeric,
zweirad numeric,
moped numeric,
fahrrad numeric,
anftag numeric,
datanf character varying,
normal numeric,
krankmo numeric,
krankdi numeric,
krankmi numeric,
krankdo numeric,
krankfr numeric,
kranksa numeric,
krankso numeric,
werkmo numeric,
werkdi numeric,
werkmi numeric,
werkdo numeric,
werkfr numeric,
werksa numeric,
werkso numeric,
urlaubmo numeric,
urlaubdi numeric,
urlaubmi numeric,
urlaubdo numeric,
urlaubfr numeric,
urlaubsa numeric,
urlaubso numeric,
anorm1mo numeric,
anorm1di numeric,
anorm1mi numeric,
anorm1do numeric,
anorm1fr numeric,
anorm1sa numeric,
anorm1so numeric,
anorm2mo numeric,
anorm2di numeric,
anorm2mi numeric,
anorm2do numeric,
anorm2fr numeric,
anorm2sa numeric,
anorm2so numeric,
gewhhpwo numeric
);

create view view_mop1994_persons as select
id as "Haushalts-ID",
persnr as "Personen-ID",
jahr as "Erhebungsjahr",
ausfueller as "Ausfüllender",
sex as "Geschlecht",
gebjahr as "Geburtsjahr",
alter as "Altersklasse",
schulab as "höchster Schulabschluss",
beruf as "Berufstätigkeit",
wechsarb as "Wechsel Arbeits- / Ausbildungsplatz im letzten Jahr",
lagearb as "Lage des Arbeits- / Ausbildungsplatzes / der Schule...",
oefferr as "Erreichbarkeit des Arbeits... mit ÖV",
fussmin as "Fußweg von Haltestelle Arbeits...",
parkp as "Parkplatzsituation am Arbeits...",
fspkw as "Pkw-Führerschein",
fsmot as "Motorrad-Führerschein",
pkwverf as "Pkw-Verfügbarkeit",
zeitopnv as "Zeitkarte für ÖV vorhanden",
bahncard as "Bahncard vorhanden",
zweirad as "Zweirad vorhanden",
moped as "Mofa / Moped / Motorrad vorhanden",
fahrrad as "Fahrrad vorhanden",
anftag as "Wochentag des Beginns des Berichts",
datanf as "Datum des Beginns des Berichts",
normal as "mehr oder weniger Besonderheiten in den Berichtstagen",
krankmo as "Person war Montag krank",
krankdi as "Person war Dienstag krank",
krankmi as "Person war Mittwoch krank",
krankdo as "Person war Donnerstag krank",
krankfr as "Person war Freitag krank",
kranksa as "Person war Samstag krank",
krankso as "Person war Sonntag krank",
werkmo as "Pkw war Montag in Werkstatt",
werkdi as "Pkw war Dienstag in Werkstatt",
werkmi as "Pkw war Mittwoch in Werkstatt",
werkdo as "Pkw war Donnerstag in Werkstatt",
werkfr as "Pkw war Freitag in Werkstatt",
werksa as "Pkw war Samstag in Werkstatt",
werkso as "Pkw war Sonntag in Werkstatt",
urlaubmo as "Person war Montag im Urlaub",
urlaubdi as "Person war Dienstag im Urlaub",
urlaubmi as "Person war Mittwoch im Urlaub",
urlaubdo as "Person war Donnerstag im Urlaub",
urlaubfr as "Person war Freitag im Urlaub",
urlaubsa as "Person war Samstag im Urlaub",
urlaubso as "Person war Sonntag im Urlaub",
anorm1mo as "andere Besonderheiten am Montag: erste Nennung",
anorm1di as "andere Besonderheiten am Dienstag: erste Nennung",
anorm1mi as "andere Besonderheiten am Mittwoch: erste Nennung",
anorm1do as "andere Besonderheiten am Donnerstag: erste Nennung",
anorm1fr as "andere Besonderheiten am Freitag: erste Nennung",
anorm1sa as "andere Besonderheiten am Samstag: erste Nennung",
anorm1so as "andere Besonderheiten am Sonntag: erste Nennung",
anorm2mo as "andere Besonderheiten am Montag: zweite Nennung",
anorm2di as "andere Besonderheiten am Dienstag: zweite Nennung",
anorm2mi as "andere Besonderheiten am Mittwoch: zweite Nennung",
anorm2do as "andere Besonderheiten am Donnerstag: zweite Nennung",
anorm2fr as "andere Besonderheiten am Freitag: zweite Nennung",
anorm2sa as "andere Besonderheiten am Samstag: zweite Nennung",
anorm2so as "andere Besonderheiten am Sonntag: zweite Nennung",
gewhhpwo as "kombinierter Gewichtungsfaktor"
from mop1994.persons;

//ab 1997
create table mop1994.persons(
id character varying,
persnr character varying,
jahr numeric,
ausfueller numeric,
sex numeric,
gebjahr numeric,
alter numeric,
schulab numeric,
beruf numeric,
wechsarb numeric,
lagearb numeric,
oefferr numeric,
fussmin numeric,
parkp numeric,
fspkw numeric,
fsmot numeric,
pkwverf numeric,
zeitopnv numeric,
bahncard numeric,
moped numeric,
fahrrad numeric,
anftag numeric,
datanf character varying,
normal numeric,
krankmo numeric,
krankdi numeric,
krankmi numeric,
krankdo numeric,
krankfr numeric,
kranksa numeric,
krankso numeric,
werkmo numeric,
werkdi numeric,
werkmi numeric,
werkdo numeric,
werkfr numeric,
werksa numeric,
werkso numeric,
urlaubmo numeric,
urlaubdi numeric,
urlaubmi numeric,
urlaubdo numeric,
urlaubfr numeric,
urlaubsa numeric,
urlaubso numeric,
anorm1mo numeric,
anorm1di numeric,
anorm1mi numeric,
anorm1do numeric,
anorm1fr numeric,
anorm1sa numeric,
anorm1so numeric,
anorm2mo numeric,
anorm2di numeric,
anorm2mi numeric,
anorm2do numeric,
anorm2fr numeric,
anorm2sa numeric,
anorm2so numeric,
gewhhpwo numeric
);

//ab 2004
create table mop1994.persons(
id character varying,
persnr character varying,
jahr numeric,
ausfueller numeric,
sex numeric,
gebjahr numeric,
alter numeric,
mobeinschr numeric,
schulab numeric,
beruf numeric,
wechsarb numeric,
lagearb numeric,
oefferr numeric,
fussmin numeric,
parkp numeric,
fspkw numeric,
fsmot numeric,
pkwverf numeric,
zeitopnv numeric,
bahncard numeric,
zweirad numeric,
moped numeric,
fahrrad numeric,
anftag numeric,
datanf character varying,
normal numeric,
krankmo numeric,
krankdi numeric,
krankmi numeric,
krankdo numeric,
krankfr numeric,
kranksa numeric,
krankso numeric,
werkmo numeric,
werkdi numeric,
werkmi numeric,
werkdo numeric,
werkfr numeric,
werksa numeric,
werkso numeric,
urlaubmo numeric,
urlaubdi numeric,
urlaubmi numeric,
urlaubdo numeric,
urlaubfr numeric,
urlaubsa numeric,
urlaubso numeric,
anorm1mo numeric,
anorm1di numeric,
anorm1mi numeric,
anorm1do numeric,
anorm1fr numeric,
anorm1sa numeric,
anorm1so numeric,
anorm2mo numeric,
anorm2di numeric,
anorm2mi numeric,
anorm2do numeric,
anorm2fr numeric,
anorm2sa numeric,
anorm2so numeric,
gewhhpwo numeric
);

create table mop1994.children(
id character varying,
persnr character varying,
jahr numeric,
ausfueller numeric,
sex numeric,
gebjahr numeric,
beruf numeric,
wechsarb numeric,
lagearb numeric,
oefferr numeric,
fussmin numeric,
parkp numeric,
zeitopnv numeric,
bahncard numeric,
zweirad numeric,
fahrrad numeric
);

create view view_mop1994_persons as select
id as "Haushalts-ID",
persnr as "Personen-ID",
jahr as "Erhebungsjahr",
ausfueller as "Ausfüllender",
sex as "Geschlecht",
gebjahr as "Geburtsjahr",
beruf as "Berufstätigkeit",
wechsarb as "Wechsel Arbeits- / Ausbildungsplatz im letzten Jahr",
lagearb as "Lage des Arbeits- / Ausbildungsplatzes / der Schule...",
oefferr as "Erreichbarkeit des Arbeits... mit ÖV",
fussmin as "Fußweg von Haltestelle Arbeits...",
parkp as "Parkplatzsituation am Arbeits...",
zeitopnv as "Zeitkarte für ÖV vorhanden",
bahncard as "Bahncard vorhanden",
zweirad as "Zweirad vorhanden",
fahrrad as "Fahrrad vorhanden"
from mop1994.children;
