create table mop1994.households(
id character varying,
jahr numeric,
bik numeric,
raumtyp numeric,
bflr numeric,
region numeric,
kreis numeric,
gemeinde numeric,
plz numeric,
gkz numeric,
ewzahl numeric,
wetter numeric,
umzug numeric,
lage numeric,
hhtyp numeric,
hhgro numeric,
p0_10 numeric,
einko numeric,
pkwhh numeric,
pkwpriv1 numeric,
pkwpriv2 numeric,
pkwpriv3 numeric,
pkwnutz1 numeric,
pkwnutz2 numeric,
pkwnutz3 numeric,
parkstr1 numeric,
parkstr2 numeric,
parkstr3 numeric,
parkgar numeric,
parkprob numeric,
haltbus numeric,
haltbusz numeric,
haltstr numeric,
haltstrz numeric,
haltu numeric,
haltuz numeric,
halts numeric,
haltsz numeric,
haltzug numeric,
haltzugz numeric,
oeffzuf numeric,
eink1 numeric,
eink1km numeric,
eink2 numeric,
eink2km numeric,
kneipe numeric,
kneipekm numeric,
kino numeric,
kinokm numeric,
sport numeric,
sportkm numeric,
zweitw numeric,
zweitwkm numeric,
carshar numeric,
handy numeric,
pc numeric,
pcweb numeric,
gewhhwo numeric
);

copy mop1994.households from '/home/dhosse/Dokumente/10_data/MoP/1994/Haushalte.csv' delimiter ';'

create view view_mop1994_households as select
id as "Haushalts-ID",
jahr as "Erhebungsjahr",
bik as "Raumtyp nach BIK",
raumtyp as "Raumtyp nach BIK (zusammengefasst)",
bflr as "BFLR",
region as "Regionstyp nach BFLR/BBR",
kreis as "Kreistyp nach BFLR/BBR",
gemeinde as "Gemeindetyp nach BFLR/BBR",
plz as "Postleitzahl",
gkz as "Gemeindekennzahl",
ewzahl as "politische Gemeindegrößenklasse",
wetter as "Zuordnung des HH-Standorts in den Wetterbereich der Wetterstationen",
umzug as "Umzug im vergangenen Jahr",
lage as "Lage der Wohnung des HH (Selbsteinschätzung)",
hhtyp as "Haushaltstyp",
hhgro as "Anzahl Personen",
p0_10 as "Anzahl Kinder",
einko as "monatliches Haushaltseinkommen",
pkwhh as "Anzahl Pkw",
pkwpriv1 as "Eigentumsverhältnis des Erstwagens",
pkwpriv2 as "Eigentumsverhältnis des Zweitwagens",
pkwpriv3 as "Eigentumsverhältnis des Drittwagens",
pkwnutz1 as "Nutzung des Erstwagens",
pkwnutz2 as "Nutzung des Zweitwagens",
pkwnutz3 as "Nutzung des Drittwagens",
parkstr1 as "Angabe des Parkplatzes des Erstwagens",
parkstr2 as "Angabe des Parkplatzes des Zweitwagens",
parkstr3 as "Angabe des Parkplatzes des Drittwagens",
parkgar as "Garage oder privater Parkplatz vorhanden",
parkprob as "Schwierigkeit, in der Nähe der Wohnung einen Parkplatz zu finden",
haltbus as "Bushaltestelle zu Fuß zu erreichen",
haltbusz as "Dauer des Fußwegs von Wohnung zur Bushaltestelle",
haltstr as "Straßenbahnhaltestelle zu Fuß zu erreichen",
haltstrz as "Dauer des Fußwegs von Wohnung zu Straßenbahnhaltestelle",
haltu as "U-Bahn-Haltestelle zu Fuß zu erreichen",
haltuz as "Dauer des Fußwegs von Wohnung zu U-Bahn-Haltestelle",
halts as "S-Bahn-Haltestelle zu Fuß zu erreichen",
haltsz as "Dauer des Fußwegs von Wohnung zu S-Bahn-Haltestelle",
haltzug as "Bahnhof zu Fuß zu erreichen",
haltzugz as "Dauer des Fußwegs von Wohnung zu Bahnhof",
oeffzuf as "Zufriedenheit mit ÖV-Anbindung",
eink1 as "Einkaufsmöglichkeit für täglichen Bedarf (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
eink1km as "Entfernung zur nächsten Einkaufsmöglichkeit für täglichen Bedarf [km]",
eink2 as "Einkaufsmöglichkeit (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
eink2km as "Entfernung zur nächsten Einkaufsmöglichkeit [km]",
kneipe as "Kneipe / Café (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
kneipekm as "Entfernung zur nächsten Kneipe / Café [km]",
kino as "Ausgehmöglichkeiten (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
kinokm as "Entfernung zur nächsten Ausgehmöglichkeit [km]",
sport as "Sportstätten (1-2 km bzw. 15 - 20 min Fußweg) vorhanden",
sportkm as "Entfernung zur nächsten Sportstätte [km]",
zweitw as "Zweitwohnsitz vorhanden",
zweitwkm as "Entfernung zum Zweitwohnsitz [km]",
carshar as "Carsharing-Mitglied im Haushalt",
handy as "Anzahl Handys im Haushalt",
pc as "PC im Haushalt",
pcweb as "Internetzugang",
gewhhwo as "Hochrechnenfaktor"
from mop1994.households;
