create table mid2008.households(
hhid character varying,
sourceid numeric,
hh_gew numeric,
h01 numeric,
h02 numeric,
p1nr numeric,
p2nr numeric,
p3nr numeric,
p4nr numeric,
p5nr numeric,
p6nr numeric,
p7nr numeric,
p8nr numeric,
hpalter1 numeric,
hpalter2 numeric,
hpalter3 numeric,
hpalter4 numeric,
hpalter5 numeric,
hpalter6 numeric,
hpalter7 numeric,
hpalter8 numeric,
hp_sex1 numeric,
hp_sex2 numeric,
hp_sex3 numeric,
hp_sex4 numeric,
hp_sex5 numeric,
hp_sex6 numeric,
hp_sex7 numeric,
hp_sex8 numeric,
hp_beru1 numeric,
hp_beru2 numeric,
hp_beru3 numeric,
hp_beru4 numeric,
hp_beru5 numeric,
hp_beru6 numeric,
hp_beru7 numeric,
hp_beru8 numeric,
hp_bkat1 numeric,
hp_bkat2 numeric,
hp_bkat3 numeric,
hp_bkat4 numeric,
hp_bkat5 numeric,
hp_bkat6 numeric,
hp_bkat7 numeric,
hp_bkat8 numeric,
hp_taet1 numeric,
hp_taet2 numeric,
hp_taet3 numeric,
hp_taet4 numeric,
hp_taet5 numeric,
hp_taet6 numeric,
hp_taet7 numeric,
hp_taet8 numeric,
hpbesch1 numeric,
hpbesch2 numeric,
hpbesch3 numeric,
hpbesch4 numeric,
hpbesch5 numeric,
hpbesch6 numeric,
hpbesch7 numeric,
hpbesch8 numeric,
hpkwfs1 numeric,
hpkwfs2 numeric,
hpkwfs3 numeric,
hpkwfs4 numeric,
hpkwfs5 numeric,
hpkwfs6 numeric,
hpkwfs7 numeric,
hpkwfs8 numeric,
h04_1 numeric,
h04_2 numeric,
h04_3 numeric,
h040_1 numeric,
h040_2 numeric,
h040_3 numeric,
h040_4 numeric,
h040_5 numeric,
h040_6 numeric,
h040_7 numeric,
h040_8 numeric,
grkpkw numeric,
hheink numeric,
oek_stat numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp numeric,
klasse_h numeric,
status_h numeric,
fahrlj_h numeric,
co2tag_h numeric,
bland numeric,
westost numeric,
polgk numeric,
rtyp numeric,
rtypd7 numeric,
ktyp numeric,
ktyp_zsg numeric,
sgtyp numeric,
sgtypd numeric,
psu_nr numeric
);

copy mid2008.households from '/home/dhosse/MiD2008_PUF_Haushalte2.csv' DELIMITER ';'

create view Haushalte_MiD2008 as
select
hhid as "Haushalts-ID",
sourceid as "Methode des Haushalts-Interviews",
hh_gew as "Gewichtungsfaktor Haushate",
h01 as "Leben Sie in Ihrem Haushalt...",
h02 as "Anzahl Personen im Haushalt",
p1nr as "Person 1",
p2nr as "Person 2",
p3nr as "Person 3",
p4nr as "Person 4",
p5nr as "Person 5",
p6nr as "Person 6",
p7nr as "Person 7",
p8nr as "Person 8",
hpalter1 as "Alter Person 1",
hpalter2 as "Alter Person 2",
hpalter3 as "Alter Person 3",
hpalter4 as "Alter Person 4",
hpalter5 as "Alter Person 5",
hpalter6 as "Alter Person 6",
hpalter7 as "Alter Person 7",
hpalter8 as "Alter Person 8",
...//TODO
from households

CREATE TABLE mid2008.persons (
hhid character varying,
pid character varying,
p_gew character varying,
int_typ9 numeric,
p01_1 numeric,
p02 numeric,
p021 numeric,
p033 numeric,
p031 numeric,
p032 numeric,
p034 numeric,
p035 numeric,
p052 numeric,
p054 numeric,
hp_sex numeric,
hp_alter numeric,
hp_altg1 numeric,
hp_altg2 numeric,
hp_altg3 numeric,
hp_beruf numeric,
hp_bkat numeric,
hp_taet numeric,
hp_besch numeric,
p14a numeric,
p14b numeric,
p14_1 numeric,
p16_1 numeric,
p0411_3 numeric,
p0411_4 numeric,
p0412_1 numeric,
p0412_2 numeric,
p0412_3 numeric,
p0412_4 numeric,
p0413_1 numeric,
p0413_2 numeric,
p0413_3 numeric,
p0413_4 numeric,
p0413 numeric,
p0414_1 numeric,
p0414_2 numeric,
p0414_3 numeric,
p0414_4 numeric,
p070 numeric,
p070_a numeric,
p10 numeric,
p06 numeric,
p061_1 numeric,
p061_2 numeric,
p061_3 numeric,
hp_pkwfs numeric,
p061_4 numeric,
p061_5 numeric,
p061_6 numeric,
p061_1j numeric,
p061_2j numeric,
p061_3j numeric,
p061_4j numeric,
"p19.1_1" numeric,
"p19.1_2" numeric,
"p19.1_3" numeric,
"p19.1_4" numeric,
"p19.1_5" numeric,
"p19.1_6" numeric,
p091_1 numeric,
p091_2 numeric,
p091_3 numeric,
p091_4 numeric,
p091_5 numeric,
p091_6 numeric,
gesein numeric,
p092 numeric,
p08 numeric,
s03 numeric,
s04 numeric,
s01 numeric,
s02_1 numeric,
s02_2 numeric,
s02_3 numeric,
s02_4 numeric,
s02_5 numeric,
s02_6 numeric,
s02_7 numeric,
mobil numeric,
rbw0 numeric,
rbw1 numeric,
rbw02 numeric,
rbw03 numeric,
rbw04 numeric,
rbw05 numeric,
w12 numeric,
wege1 numeric,
wege2 numeric,
wege3 numeric,
anzkm numeric,
anzmin numeric,
pergrup numeric,
pergrup1 numeric,
lebensph numeric,
ov_seg numeric,
co2tag_p numeric,
stich_j numeric,
stich_m numeric,
stichtag numeric,
stichwo numeric,
saison numeric,
hheink numeric,
oek_stat numeric,
h02 numeric,
h04_3 numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp numeric,
bland numeric,
westost numeric,
polgk numeric,
rtyp numeric,
rtypd7 numeric,
ktyp numeric,
ktyp_zsg numeric,
sgtyp numeric,
sgtypd numeric,
psu_nr numeric
);

copy mid2008.persons from '/home/dhosse/MiD2008_PUF_Personen2.csv' DELIMITER ';'

create table mid2008.ways(
hhid character varying,
pid character varying,
wid character varying,
wsid character varying,
w_gew numeric,
wsource numeric,
int_typ9 numeric,
stich_j numeric,
stich_m numeric,
stichtag numeric,
stichwo numeric,
saison numeric,
st_time numeric,
st_std numeric,
st_min numeric,
st_stdg numeric,
en_time numeric,
en_std numeric,
en_min numeric,
st_dat numeric,
en_dat numeric,
w04 numeric,
w04_dzw numeric,
w04_sons text,
hwzweck numeric,
w01 numeric,
w13 numeric,
w044 numeric,
w05_1 numeric,
w05_2 numeric,
w05_3 numeric,
w05_4 numeric,
mrad_f numeric,
mrad_mf numeric,
w05_5 numeric,
pkw_f numeric,
pkw_mf numeric,
w05_7 numeric,
lkw_f numeric,
lkw_mf numeric,
w05_11 numeric,
w05_12 numeric,
w05_13 numeric,
w05_14 numeric,
w05_15 numeric,
w05_16 numeric,
w05_17 numeric,
w05_18 numeric,
w05_20 numeric,
w05_22 numeric,
w05_23 numeric,
hvm_diff numeric,
hvm numeric,
hvm_oev numeric,
vm_kombi numeric,
w061 numeric,
w062 numeric,
w063 numeric,
w07 numeric,
anzpers numeric,
w071 numeric,
w072_1 numeric,
w072_2 numeric,
w072_3 numeric,
w072_4 numeric,
w072_5 numeric,
w072_6 numeric,
w072_7 numeric,
w072_8 numeric,
w072_9 numeric,
w072_10 numeric,
w073 numeric,
w074 numeric,
begleit numeric,
wegkm_k numeric,
wegmin_k numeric,
tempo numeric,
co2weg numeric,
kraftweg numeric,
hheink numeric,
oek_stat numeric,
h02 numeric,
h04_3 numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp numeric,
hp_sex numeric,
hp_alter numeric,
hp_altg1 numeric,
hp_altg2 numeric,
hp_altg3 numeric,
hp_besch numeric,
hp_pkwfs numeric,
pergrup numeric,
pergrup1 numeric,
p070 numeric,
lebensph numeric,
gesein numeric,
ov_seg numeric,
s03 numeric,
s04 numeric,
s01 numeric,
s02_1 numeric,
s02_2 numeric,
s02_3 numeric,
s02_4 numeric,
s02_5 numeric,
s02_6 numeric,
s02_7 numeric,
bland numeric,
westost numeric,
polgk numeric,
rtyp numeric,
rtypd7 numeric,
ktyp numeric,
ktyp_zsg numeric,
sgtyp numeric,
sgtypd numeric,
psu_nr numeric
)

copy mid2008.ways from '/home/dhosse/MiD2008_PUF_Wege2.csv' DELIMITER ';'
