create table mid2008.cars(
hhid character varying,
vmid character varying,
sourceid character varying,
a_gew numeric,
h041 character varying,
h042 character varying,
h044 character varying,
h046 character varying,
h048 character varying,
ps numeric,
kW numeric,
h0411 character varying,
h0416 character varying,
h0412 numeric,
h0413 numeric,
h0414 numeric,
fahrlj numeric,
klasse character varying,
status character varying,
seg_kba character varying,
anzfahrt numeric,
gesfkm numeric,
durchkm numeric,
gesfmin numeric,
durchmin numeric,
anzfpers numeric,
besgrad numeric,
stich_j numeric,
stich_m character varying,
stichtag character varying,
stichwo numeric,
sex_hn character varying,
alter_hn numeric,
besch_hn character varying,
hheink character varying,
oek_stat character varying,
h02 numeric,
h04_3 numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp character varying,
bland character varying,
westost character varying,
polgk character varying,
rtyp character varying,
rtypd7 character varying,
ktyp character varying,
ktyp_zsg character varying,
sgtyp character varying,
sgtypd character varying,
psu_nr numeric
)

copy mid2008.cars from '/home/dhosse/Autos_l.csv' delimiter ';'

create view view_mid2008_cars as
select
hhid as "Haushalts-ID",
vmid as "Fahrzeug-ID",
sourceid as "Interview-Methode",
a_gew as "Gewichtungsfaktor Autos",
h041 as "Hersteller",
h042 as "Modellbezeichnung",
h044 as "Hauptnutzer (Personen-ID)",
h046 as "Zulassungsart",
h048 as "Antriebstechnologie",
ps as "PS",
kW as "kW",
h0411 as "Üblicher Stellplatz",
h0416 as "Stellplatzsuche",
h0412 as "Baujahr",
h0413 as "Anschaffungsjahr",
h0414 as "aktueller Kilometerstand",
fahrlj as "Fahrleistung [km/Jahr]",
klasse as "Typklasse (nach Hersteller und Leistung)",
status as "Statusklasse (nach Typklasse und Baujahr)",
seg_kba as "PKW-Segmenteinteilung nach KBA",
anzfahrt as "Fahrten am Stichtag",
gesfkm as "Gesamtstrecke am Stichtag [km]",
durchkm as "durchschnittliche Entfernung der Fahrten am Stichtag [km]",
gesfmin as "Gesamtfahrzeit am Stichtag [min]",
durchmin as "durchschnittliche Fahrdauer am Stichtag [min]",
anzfpers as "Anzahl beförderter Personen am Stichtag",
besgrad as "durchschnittlicher Besetzungsgrad am Stichtag",
stich_j as "Stichtag (Kalenderjahr)",
stich_m as "Stichtag (Kalendermonat)",
stichtag as "Stichtag (Wochentag)",
stichwo as "Stichtag (Kalenderwoche)",
sex_hn as "Geschlecht Hauptnutzer",
alter_hn as "Alter Hauptnutzer",
besch_hn as "Beschäftigung Hauptnutzer",
hheink as "Haushaltseinkommen [€/Monat]",
oek_stat as "ökonomischer Status",
h02 as "Anzahl Personen im Haushalt",
h04_3 as "Anzahl Autos im Haushalt",
hhgr06 as "Personen unter 6 Jahren",
hhgr14 as "Personen unter 14 Jahren",
hhgr18 as "Personen unter 18 Jahren",
anzerw as "Personen über 18 Jahren",
hhtyp as "Haushaltstyp",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeinegröße",
rtyp as "BBSR-Regiongrundtyp",
rtypd7 as "BBSR differenzierter Regionsgrundtyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBSR zuammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.cars;

create table mid2008.households(
hhid character varying,
sourceid character varying,
hh_gew numeric,
h01 character varying,
h02 numeric,
p1nr numeric,
p2nr numeric,
p3nr numeric,
p4nr numeric,
p5nr numeric,
p6nr numeric,
p7nr numeric,
p8nr numeric,
hpalter1 numeric,
hpalter2 numeric,
hpalter3 numeric,
hpalter4 numeric,
hpalter5 numeric,
hpalter6 numeric,
hpalter7 numeric,
hpalter8 numeric,
hp_sex1 character varying,
hp_sex2 character varying,
hp_sex3 character varying,
hp_sex4 character varying,
hp_sex5 character varying,
hp_sex6 character varying,
hp_sex7 character varying,
hp_sex8 character varying,
hp_beru1 character varying,
hp_beru2 character varying,
hp_beru3 character varying,
hp_beru4 character varying,
hp_beru5 character varying,
hp_beru6 character varying,
hp_beru7 character varying,
hp_beru8 character varying,
hp_bkat1 character varying,
hp_bkat2 character varying,
hp_bkat3 character varying,
hp_bkat4 character varying,
hp_bkat5 character varying,
hp_bkat6 character varying,
hp_bkat7 character varying,
hp_bkat8 character varying,
hp_taet1 character varying,
hp_taet2 character varying,
hp_taet3 character varying,
hp_taet4 character varying,
hp_taet5 character varying,
hp_taet6 character varying,
hp_taet7 character varying,
hp_taet8 character varying,
hpbesch1 character varying,
hpbesch2 character varying,
hpbesch3 character varying,
hpbesch4 character varying,
hpbesch5 character varying,
hpbesch6 character varying,
hpbesch7 character varying,
hpbesch8 character varying,
hpkwfs1 character varying,
hpkwfs2 character varying,
hpkwfs3 character varying,
hpkwfs4 character varying,
hpkwfs5 character varying,
hpkwfs6 character varying,
hpkwfs7 character varying,
hpkwfs8 character varying,
h04_1 numeric,
h04_2 numeric,
h04_3 numeric,
h040_1 character varying,
h040_2 character varying,
h040_3 character varying,
h040_4 character varying,
h040_5 character varying,
h040_6 character varying,
h040_7 character varying,
h040_8 character varying,
grkpkw character varying,
hheink character varying,
oek_stat character varying,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp character varying,
klasse_h character varying,
status_h character varying,
fahrlj_h numeric,
co2tag_h numeric,
bland character varying,
westost character varying,
polgk character varying,
rtyp character varying,
rtypd7 character varying,
ktyp character varying,
ktyp_zsg character varying,
sgtyp character varying,
sgtypd character varying,
psu_nr numeric
);

copy mid2008.households from '/home/dhosse/Haushalte_l.csv' delimiter ';'

create view view_mid2008_households as
select
hhid as "Haushalts-ID",
sourceid as "Interview-Methode",
hh_gew as "Gewichtungsfaktor Haushalte",
h01 as "Leben Sie in Ihrem Haushalt...",
h02 as "Anzahl Personen im Haushalt",
p1nr as "Person 1",
p2nr as "Person 2",
p3nr as "Person 3",
p4nr as "Person 4",
p5nr as "Person 5",
p6nr as "Person 6",
p7nr as "Person 7",
p8nr as "Person 8",
hpalter1 as "Person 1 Alter",
hpalter2 as "Person 2 Alter",
hpalter3 as "Person 3 Alter",
hpalter4 as "Person 4 Alter",
hpalter5 as "Person 5 Alter",
hpalter6 as "Person 6 Alter",
hpalter7 as "Person 7 Alter",
hpalter8 as "Person 8 Alter",
hp_sex1 as "Person 1 Geschlecht",
hp_sex2 as "Person 2 Geschlecht",
hp_sex3 as "Person 3 Geschlecht",
hp_sex4 as "Person 4 Geschlecht",
hp_sex5 as "Person 5 Geschlecht",
hp_sex6 as "Person 6 Geschlecht",
hp_sex7 as "Person 7 Geschlecht",
hp_sex8 as "Person 8 Geschlecht",
hp_beru1 as "Person 1 berufstätig",
hp_beru2 as "Person 2 berufstätig",
hp_beru3 as "Person 3 berufstätig",
hp_beru4 as "Person 4 berufstätig",
hp_beru5 as "Person 5 berufstätig",
hp_beru6 as "Person 6 berufstätig",
hp_beru7 as "Person 7 berufstätig",
hp_beru8 as "Person 8 berufstätig",
hp_bkat1 as "Person 1 Arbeitszeit",
hp_bkat2 as "Person 2 Arbeitszeit",
hp_bkat3 as "Person 3 Arbeitszeit",
hp_bkat4 as "Person 4 Arbeitszeit",
hp_bkat5 as "Person 5 Arbeitszeit",
hp_bkat6 as "Person 6 Arbeitszeit",
hp_bkat7 as "Person 7 Arbeitszeit",
hp_bkat8 as "Person 8 Arbeitszeit",
hp_taet1 as "Person 1 Tätigkeit",
hp_taet2 as "Person 2 Tätigkeit",
hp_taet3 as "Person 3 Tätigkeit",
hp_taet4 as "Person 4 Tätigkeit",
hp_taet5 as "Person 5 Tätigkeit",
hp_taet6 as "Person 6 Tätigkeit",
hp_taet7 as "Person 7 Tätigkeit",
hp_taet8 as "Person 8 Tätigkeit",
hpbesch1 as "Person 1 Tätigkeit und Arbeitszeit",
hpbesch2 as "Person 2 Tätigkeit und Arbeitszeit",
hpbesch3 as "Person 3 Tätigkeit und Arbeitszeit",
hpbesch4 as "Person 4 Tätigkeit und Arbeitszeit",
hpbesch5 as "Person 5 Tätigkeit und Arbeitszeit",
hpbesch6 as "Person 6 Tätigkeit und Arbeitszeit",
hpbesch7 as "Person 7 Tätigkeit und Arbeitszeit",
hpbesch8 as "Person 8 Tätigkeit und Arbeitszeit",
hpkwfs1 as "Person 1 Pkw-Führerschein",
hpkwfs2 as "Person 2 Pkw-Führerschein",
hpkwfs3 as "Person 3 Pkw-Führerschein",
hpkwfs4 as "Person 4 Pkw-Führerschein",
hpkwfs5 as "Person 5 Pkw-Führerschein",
hpkwfs6 as "Person 6 Pkw-Führerschein",
hpkwfs7 as "Person 7 Pkw-Führerschein",
hpkwfs8 as "Person 8 Pkw-Führerschein",
h04_1 as "Anzahl Fahrräder",
h04_2 as "Anzahl Motorräder, Mopeds, Mofas",
h04_3 as "Anzahl Autos",
h040_1 as "kein Auto weil nicht nötig",
h040_2 as "bewusster Verzicht auf ein Auto",
h040_3 as "Auto ist zu teuer",
h040_4 as "kein Auto aus gesundheitlichen Gründen",
h040_5 as "kein Auto aus Altersgründen",
h040_6 as "kein Auto aus anderen Gründen",
h040_7 as "Aussage zu Nicht-Pkw-Besitz verweigert",
h040_8 as "weiß nicht",
grkpkw as "Hauptgrund für Nicht-Pkw-Besitz",
hheink as "Haushaltseinkommen [€/Monat]",
oek_stat as "ökonomischer Status",
hhgr06 as "Personen unter 6 Jahren",
hhgr14 as "Personen unter 14 Jahren",
hhgr18 as "Personen unter 18 Jahren",
anzerw as "Personen über 18 Jahren",
hhtyp as "Haushaltstyp",
klasse_h as "höchste Auto-Typklasse",
status_h as "höchster Auto-Status",
fahrlj_h as "Fahrleistung [km/Jahr]",
co2tag_h as "CO2-Emissionen [kg/Stichtag]",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeindegrößenklasse",
rtyp as "BBSR Regionsgrundtyp",
rtypd7 as "BBSR differenzierter Regionstyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBR zusammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.households;

CREATE TABLE mid2008.persons (
hhid character varying,
pid character varying,
p_gew numeric,
int_typ9 character varying,
p01_1 character varying,
p02 character varying,
p021 character varying,
p033 character varying,
p031 character varying,
p032 character varying,
p034 character varying,
p035 character varying,
p052 character varying,
p054 character varying,
hp_sex character varying,
hp_alter character varying,
hp_altg1 character varying,
hp_altg2 character varying,
hp_altg3 character varying,
hp_beruf character varying,
hp_bkat character varying,
hp_taet character varying,
hp_besch character varying,
p14a character varying,
p14b character varying,
p14_1 character varying,
p16_1 character varying,
p0411_3 character varying,
p0411_4 character varying,
p0412_1 character varying,
p0412_2 character varying,
p0412_3 character varying,
p0412_4 character varying,
p0413_1 character varying,
p0413_2 character varying,
p0413_3 character varying,
p0413_4 character varying,
p0413 character varying,
p0414_1 character varying,
p0414_2 character varying,
p0414_3 character varying,
p0414_4 character varying,
p070 character varying,
p070_a character varying,
p10 numeric,
p06 character varying,
p061_1 character varying,
p061_2 character varying,
p061_3 character varying,
hp_pkwfs character varying,
p061_4 character varying,
p061_5 character varying,
p061_6 character varying,
p061_1j numeric,
p061_2j numeric,
p061_3j numeric,
p061_4j numeric,
"p19.1_1" character varying,
"p19.1_2" character varying,
"p19.1_3" character varying,
"p19.1_4" character varying,
"p19.1_5" character varying,
"p19.1_6" character varying,
p091_1 character varying,
p091_2 character varying,
p091_3 character varying,
p091_4 character varying,
p091_5 character varying,
p091_6 character varying,
gesein character varying,
p092 character varying,
p08 character varying,
s03 character varying,
s04 character varying,
s01 character varying,
s02_1 character varying,
s02_2 character varying,
s02_3 character varying,
s02_4 character varying,
s02_5 character varying,
s02_6 character varying,
s02_7 character varying,
mobil character varying,
rbw0 character varying,
rbw1 character varying,
rbw02 character varying,
rbw03 numeric,
rbw04 numeric,
rbw05 character varying,
w12 numeric,
wege1 numeric,
wege2 numeric,
wege3 numeric,
anzkm numeric,
anzmin numeric,
pergrup character varying,
pergrup1 character varying,
lebensph character varying,
ov_seg character varying,
co2tag_p numeric,
stich_j numeric,
stich_m character varying,
stichtag character varying,
stichwo numeric,
saison character varying,
hheink character varying,
oek_stat character varying,
h02 numeric,
h04_3 numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp character varying,
bland character varying,
westost character varying,
polgk character varying,
rtyp character varying,
rtypd7 character varying,
ktyp character varying,
ktyp_zsg character varying,
sgtyp character varying,
sgtypd character varying,
psu_nr numeric
);

copy mid2008.persons from '/home/dhosse/Personen_l.csv' delimiter ';'

create view view_mid2008_persons as select
hhid as "Haushalts-ID",
pid as "Personen-ID",
p_gew as "Gewichtungsfaktor Personen",
int_typ9 as "Interview-Methode",
p01_1 as "Auto-Verfügbarkeit als Fahrer",
p02 as "Fahrradbesitz",
p021 as "Helm beim Fahrradfahren",
p033 as "Häufigkeit der Fahrradnutzung",
p031 as "Häufigkeit der Autonutzung",
p032 as "Häufigkeit der ÖV-Nutzung (Bus, Bahn)",
p034 as "Häufigkeit der Bahnnutzung (ab 100 km)",
p035 as "Häufigkeit der Flugzeugnutzung",
p052 as "Enternung Wohnung - Bushaltestelle",
p054 as "Entfernung Wohnung - Bahnstation (auch U-Bahn)",
hp_sex as "Geschlecht",
hp_alter as "Alter",
hp_altg1 as "Altersgruppe (Variante 1)",
hp_altg2 as "Altersgruppe (Variante 2)",
hp_altg3 as "Altersgruppe (Variante 3)",
hp_beruf as "berufstätig",
hp_bkat as "Arbeitszeit",
hp_taet as "Tätigkeit",
hp_besch as "Tätigkeit und Arbeitszeit",
p14a as "höchster allgemeinbildender Schulabschluss",
p14b as "derzeitige Schulform",
p14_1 as "Fachhochschul- oder Universitätsabschluss",
p16_1 as "Organisation der Arbeitszeit",
p0411_3 as "Erreichbarkeit Schule zu Fuß",
p0411_4 as "Erreichbarkeit Geschäfte zu Fuß",
p0412_1 as "Erreichbarkeit Arbeitsplatz Fahrrad",
p0412_2 as "Erreichbarkeit Ausbildungsplatz Fahrrad",
p0412_3 as "Erreichbarkeit Schule Fahrrad",
p0412_4 as "Erreichbarkeit Geschäfte Fahrrad",
p0413_1 as "Erreichbarkeit Arbeitsplätze ÖV",
p0413_2 as "Erreichbarkeit Ausbildungsplatz ÖV",
p0413_3 as "Erreichbarkeit Schule ÖV",
p0413_4 as "Erreichbarkeit Geschäfte ÖV",
p0413 as "Erreichbarkeit Ziele ÖV",
p0414_1 as "Erreichbarkeit Arbeitsplatz Auto",
p0414_2 as "Erreichbarkeit Ausbildungsplatz Auto",
p0414_3 as "Erreichbarkeit Schule Auto",
p0414_4 as "Erreichbarkeit Geschäfte Auto",
p070 as "überwiegende Fahrkartennutzung ÖV",
p070_a as "überwiegende Fahrscheinart ÖPNV",
p10 as "Reisen mit auswärtigen Übernachtungen (letzte 3 Monate)",
p06 as "Führerscheinbesitz",
p061_1 as "Führerscheinbesitz Moped, Mofa, Motorroller",
p061_2 as "Führerscheinbesitz Motorrad",
p061_3 as "Führerscheinbesitz Pkw",
hp_pkwfs as "Pkw-Führerschein",
p061_4 as "Führerscheinbesitz Lkw",
p061_5 as "Führerscheinbesitz: verweigert",
p061_6 as "Führerscheinbesitz: weiß nicht",
p061_1j as "Jahr des Führerscheinerwerbs (Moped, Mofa, Motorroller)",
p061_2j as "Jahr des Führerscheinerwerbs (Motorrad)",
p061_3j as "Jahr des Führerscheinerwerbs (Pkw)",
p061_4j as "Jahr des Führerscheinerwerbs (Lkw",
"p19.1_1" as "Handy regelmäßig verfügbar",
"p19.1_2" as "Computer mit Internetanschluss regelmäßig verfügbar",
"p19.1_3" as "Navigationsgerät regelmäßig verfügbar",
"p19.1_4" as "technisches Gerät regelmäßig verfügbar: nichts davon",
"p19.1_5" as "technisches Gerät regelmäßig verfügbar: verweigert",
"p19.1_6" as "technisches Gerät regelmäßig verfügbar: weiß nicht",
p091_1 as "Gehbehinderung",
p091_2 as "Sehbehinderung",
p091_3 as "andere (gesundheitliche) Einschränkung",
p091_4 as "keine körperliche Behinderung",
p091_5 as "körperliche Einschränkung: verweigert",
p091_6 as "körperliche Einschränkung: weiß nicht",
gesein as "gesundheitliche Einschränkung",
p092 as "Gefühl eingeschränkter Mobilität infolge gesundheitlicher Einschränkung",
p08 as "Wohndauer im aktuellen Ort / Wohnviertel",
s03 as "Wetter am Stichtag",
s04 as "Kfz-Verfügbarkeit für private Fahrten",
s01 as "Stichtag = normaler Tag für Sie",
s02_1 as "kein normaler Tag: Urlaub innerhalb Deutschlands",
s02_2 as "kein normaler Tag: Urlaub außerhalb Deutschlands",
s02_3 as "kein normaler Tag: Krankheit",
s02_4 as "kein normaler Tag: nicht außer Haus",
s02_5 as "kein normaler Tag: andere Gründe",
s02_6 as "kein normaler Tag: verweigert",
s02_7 as "kein normaler Tag: weiß nicht",
mobil as "Mobilität am Stichtag",
rbw0 as "regelmäßige berufliche Wege (z.B. als Postbote, Taxifahrer, ...)",
rbw1 as "Wirtschaftszweig der Beschäftigung",
rbw02 as "Hauptzweck der beruflichen Wege am Stichtag",
rbw03 as "Strecke der beruflichen Wege [km]",
rbw04 as "Anzahl der beruflichen Wege",
rbw05 as "überwiegend genutztes Verkehrsmittel auf beruflichen Wegen",
w12 as "Anzahl weiterer Wege",
wege1 as "berichtete Wege am Stichtag",
wege2 as "private Wege am Stichtag",
wege3 as "regelmäßige berufliche Wege am Stichtag",
anzkm as "Tagesstrecke [km]",
anzmin as "Unterwegszeit [min]",
pergrup as "Verhaltenshomogene Personengruppe (9 Gruppen)",
pergrup1 as "Verhaltenshomogene Personengruppe (12 Gruppen),
lebensph as "Lebensphase",
ov_seg as "Verkehrsmittel-Nutzersegment",
co2tag_p as "CO2-Emissionen am Stichtag [kg]",
stich_j as "Stichtag (Kalenderjahr)",
stich_m as "Stichtag (Kalendermonat)",
stichtag as "Stichtag (Wochtentag)",
stichwo as "Stichtag (Kalenderwoche)",
saison as "Jahreszeit",
hheink as "Haushaltseinkommen [€/Monat]",
oek_stat as "ökonomischer Status",
h02 as "Anzahl Personen im Haushalt",
h04_3 as "Anzahl Autos im Haushalt",
hhgr06 as "Anzahl Personen unter 6 Jahren",
hhgr14 as "Anzahl Personen unter 14 Jahren",
hhgr18 as "Anzahl Personen unter 18 Jahren",
anzerw as "Anzahl Personen über 18 Jahren",
hhtyp as "Haushaltstyp",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeindegrößenklasse",
rtyp as "BBSR Regionsgrundtyp",
rtypd7 as "BBSR differenzierter Regionstyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBSR zusammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.persons;

create table mid2008.ways(
hhid character varying,
pid character varying,
wid character varying,
wsid character varying,
w_gew numeric,
wsource character varying,
int_typ9 character varying,
stich_j numeric,
stich_m character varying,
stichtag character varying,
stichwo numeric,
saison character varying,
st_time numeric,
st_std numeric,
st_min numeric,
st_stdg character varying,
en_time numeric,
en_std numeric,
en_min numeric,
st_dat character varying,
en_dat character varying,
w04 character varying,
w04_dzw character varying,
w04_sons character varying,
hwzweck character varying,
w01 character varying,
w13 character varying,
w044 character varying,
w05_1 character varying,
w05_2 character varying,
w05_3 character varying,
w05_4 character varying,
mrad_f character varying,
mrad_mf character varying,
w05_5 character varying,
pkw_f character varying,
pkw_mf character varying,
w05_7 character varying,
lkw_f character varying,
lkw_mf character varying,
w05_11 character varying,
w05_12 character varying,
w05_13 character varying,
w05_14 character varying,
w05_15 character varying,
w05_16 character varying,
w05_17 character varying,
w05_18 character varying,
w05_20 character varying,
w05_22 character varying,
w05_23 character varying,
hvm_diff character varying,
hvm character varying,
hvm_oev character varying,
vm_kombi character varying,
w061 character varying,
w062 character varying,
w063 character varying,
w07 numeric,
anzpers numeric,
w071 character varying,
w072_1 character varying,
w072_2 character varying,
w072_3 character varying,
w072_4 character varying,
w072_5 character varying,
w072_6 character varying,
w072_7 character varying,
w072_8 character varying,
w072_9 character varying,
w072_10 character varying,
w073 character varying,
w074 character varying,
begleit character varying,
wegkm_k numeric,
wegmin_k numeric,
tempo numeric,
co2weg numeric,
kraftweg numeric,
hheink character varying,
oek_stat character varying,
h02 numeric,
h04_3 numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp character varying,
hp_sex character varying,
hp_alter numeric,
hp_altg1 character varying,
hp_altg2 character varying,
hp_altg3 character varying,
hp_besch character varying,
hp_pkwfs character varying,
pergrup character varying,
pergrup1 character varying,
p070 character varying,
lebensph character varying,
gesein character varying,
ov_seg character varying,
s03 character varying,
s04 character varying,
s01 character varying,
s02_1 character varying,
s02_2 character varying,
s02_3 character varying,
s02_4 character varying,
s02_5 character varying,
s02_6 character varying,
s02_7 character varying,
bland character varying,
westost character varying,
polgk character varying,
rtyp character varying,
rtypd7 character varying,
ktyp character varying,
ktyp_zsg character varying,
sgtyp character varying,
sgtypd character varying,
psu_nr numeric
)

copy mid2008.ways from '/home/dhosse/Wege_l.csv' delimiter ';'

create view view_mid2008_ways as select
hhid as "Haushalts-ID",
pid as "Personen-ID",
wid as "Wege-ID",
wsid as "sortierte Wege-ID",
w_gew as "Gewichtungsfaktor Wege",
wsource as "Quelle für Wegeangabe",
int_typ9 as "Interview-Methode",
stich_j as "Stichtag (Kalenderjahr)",
stich_m as "Stichtag (Kalendermonat)",
stichtag as "Stichtag (Wochentag)",
stichwo as "Stichtag (Kalenderwoche)",
saison as "Jahreszeit",
st_time as "Beginn Weg (Uhrzeit) [s]",
st_std as "Beginn Weg (Stunde)",
st_min as "Beginn Weg (Minute)",
st_stdg as "Startzeit des Weges gruppiert",
en_time as "Ende Weg (Uhrzeit) [s]",
en_std as "Ende Weg (Stunde)",
en_min as "Ende Weg (Minute)",
st_dat as "Beginn Weg (Stichtag / Folgetag)",
en_dat as "Ende Weg (Stichtag / Folgetag)",
w04 as "Wegezweck",
w04_dzw as "detaillierter Wegezweck",
w04_sons as "sonstiger Wegezweck",
hwzweck as "Hauptzweck des Wegs",
w01 as "Ausgangspunkt des ersten Weges",
w13 as "Lage des Zielortes",
w044 as "Führte dieser Weg...",
w05_1 as "Verkehrsmittelnutzung zu Fuß",
w05_2 as "Verkehrsmittelnutzung Fahrrad",
w05_3 as "Verkehrsmittelnutzung Moped, Mofa",
w05_4 as "Verkehrsmittelnutzung Motorrad",
mrad_f as "Verkehrsmittelnutzung Motorrad (Fahrer)",
mrad_mf as "Verkehrsmittelnutzung Motorrad (Mitfahrer)",
w05_5 as "Verkehrsmittelnutzung Auto",
pkw_f as "Verkehrsmittelnutzung Auto (Fahrer)",
pkw_mf as "Verkehrsmittelnutzung Auto (Mitfahrer)",
w05_7 as "Verkehrsmittelnutzung Lkw",
lkw_f as "Verkehrsmittelnutzung Lkw (Fahrer)",
lkw_mf as "Verkehrsmittelnutzung Lkw (Mitfahrer)",
w05_11 as "Verkehrsmittelnutzung Linienbus, Stadtbus",
w05_12 as "Verkehrsmittelnutzung U-Bahn, Straßenbahn",
w05_13 as "Verkehrsmittelnutzung S-Bahn, Nahverkehrszug",
w05_14 as "Verkehrsmittelnutzung Taxi",
w05_15 as "Verkehrsmittelnutzung Schiff, Fähre",
w05_16 as "Verkehrsmittelnutzung Fernzug",
w05_17 as "Verkehrsmittelnutzung Reisebus",
w05_18 as "Verkehrsmittelnutzung Flugzeug",
w05_20 as "Verkehrsmittelnutzung: anderes",
w05_22 as "Verkehrsmittelnutzung: verweigert",
w05_23 as "Verkehrsmittelnutzung: weiß nicht",
hvm_diff as "Haptverkehrsmittel (differenziert)",
hvm as "Hauptverkehrsmittel",
hvm_oev as "Hauptverkehrsmittel (ÖV-Variante)",
vm_kombi as "Verkehrsmittelkombination",
w061 as "Fahrer oder Mitfahrer",
w062 as "Auto aus dem Haushalt",
w063 as "Welcher Pkw aus dem Haushalt",
w07 as "Anzahl Begleiter",
anzpers as "Anzahl Personen",
w071 as "Personen aus dem Haushalt als Begleiter",
w072_1 as "Person 1 Beleiter",
w072_2 as "Person 2 Begleiter",
w072_3 as "Person 3 Begleiter",
w072_4 as "Person 4 Begleiter",
w072_5 as "Person 5 Begleiter",
w072_6 as "Person 6 Begleiter",
w072_7 as "Person 7 Begleiter",
w072_8 as "Person 8 Begleiter",
w072_9 as "andere Person Begleiter",
w072_10 as "Begleiter: weiß nicht",
w073 as "Welche Person war FahrerIn",
w074 as "Hauptzweck des Weges für Begleiter",
begleit "Charakterisierung der Begleitperson(en)",
wegkm_k as "zurückgelegte Wegstrecke [km]",
wegmin_k as "Wegedauer [min]",
tempo as "Wegegeschwindigkeit [km/h]",
co2weg as "CO2-Emission Gesamtweg [kg]",
kraftweg as "Kraftstoffverbrauch Gesamtweg [l]",
hheink as "Haushaltseinkommen",
oek_stat as "ökonomischer Status",
h02 as "Anzahl Personen im Haushalt",
h04_3 as "Anzahl Autos im Haushalt",
hhgr06 as "Anzahl Personen unter 6 Jahren",
hhgr14 as "Anzahl Personen unter 14 Jahren",
hhgr18 as "Anzahl Personen unter 18 Jahren",
anzerw as "Anzahl Personen über 18 Jahren",
hhtyp as "Haushaltstyp",
hp_sex as "Geschlecht",
hp_alter as "Alter",
hp_altg1 as "Altersgruppe (Variante 1)",
hp_altg2 as "Altersgruppe (Variante 2)",
hp_altg3 as "Altersgruppe (Variante 3)",
hp_besch as "Tätigkeit und Arbeitszeit",
hp_pkwfs as "Pkw-Führerschein",
pergrup as "Verhaltenshomogene Personengruppe (9 Gruppen)",
pergrup1 as "Verhaltenshomogene Personengruppe (12 Gruppen)",
p070 as "Reisen mit auswärtigen Übernachtungen (letzte 3 Monate)",
lebensph as "Lebensphase",
gesein as "Gesundheitliche Einschränkung",
ov_seg as "Verkehrsmittel-Nutzersegment",
s03 as "Wetter am Stichtag",
s04 as "Kfz-Verfügbarkeit für private Fahrten",
s01 as "Stichtag = normaler Tag für Sie",
s02_1 as "kein normaler Tag: Urlaub innerhalb Deutschlands",
s02_2 as "kein normaler Tag: Urlaub außerhalb Deutschlands",
s02_3 as "kein normaler Tag: Krankheit",
s02_4 as "kein normaler Tag: nicht außer Haus",
s02_5 as "kein normaler Tag: andere Gründe",
s02_6 as "kein normaler Tag: verweigert",
s02_7 as "kein normaler Tag: weiß nicht",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeindegrößenklasse",
rtyp as "BBSR Regionsgrundtyp",
rtypd7 as "BBSR differenzierter Regionstyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBSR zusammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.ways;

create table mid2008.journeys(
hhid character varying,
pid character varying,
rid character varying,
r_gew numeric,
p10 numeric,
p101 character varying,
p1012 character varying,
p1013_1 character varying,
p1013_2 character varying,
p1013_3 character varying,
p1013_4 character varying,
p1013_5 character varying,
p1013_6 character varying,
p1013_7 character varying,
p1013_8 character varying,
p1013_9 character varying,
hvm_r character varying,
p1014 numeric,
p1015 numeric,
p1016 numeric,
hheink character varying,
oek_stat character varying,
h02 numeric,
h04_3 numeric,
hhgr06 numeric,
hhgr14 numeric,
hhgr18 numeric,
anzerw numeric,
hhtyp character varying,
hp_sex character varying,
hp_alter numeric,
hp_altg1 character varying,
hp_altg2 character varying,
hp_altg3 character varying,
hp_besch character varying,
hp_pkwfs character varying,
pergrup character varying,
pergrup1 character varying,
lebensph character varying,
gesein character varying,
bland character varying,
westost character varying,
polgk character varying,
rtyp character varying,
rtypd7 character varying,
ktyp character varying,
ktyp_zsg character varying,
sgtyp character varying,
sgtypd character varying,
psu_nr numeric
)

copy mid2008.journeys from '/home/dhosse/Reisen_l.csv' delimiter ';'

create view view_mid2008_journeys as select
hhid as "Haushalts-ID",
pid as "Personen-ID",
rid as "Reise-ID",
r_gew as "Gewichtungsfaktor Reisen",
p10 as "Reisen mit auswärtiger Übernachtung (letzte 3 Monate)",
p101 as "hauptsächlicher Reisezweck",
p1012 as "Zielort",
p1013_1 as "Auto auf Hin- und Rückreise genutzt",
p1013_2 as "Bahn auf Hin- und Rückreise genutzt",
p1013_3 as "Reisebus auf Hin- und Rückreise genutzt",
p1013_4 as "Flugzeug auf Hin- und Rückreise genutzt",
p1013_5 as "Fahrrad auf Hin- und Rückreise genutzt",
p1013_6 as "Schiff auf Hin- und Rückreise genutzt",
p1013_7 as "sonstiges VM auf Hin- und Rückreise genutzt",
p1013_8 as "Aussage zu Verkehrsmittelnutzung verweigert",
p1013_9 as "weiß nicht",
hvm_r as "Hauptverkehrsmittel",
p1014 as "Anzahl auswärtiger Übernachtungen",
p1015 as "Anzahl Personen",
p1016 as "einfache Entfernung zu Hause - Reiseziel",
hheink as "Haushaltseinkommen [€/Monat]",
oek_stat as "ökonomischer Status",
h02 as "Anzahl Personen im Haushalt",
h04_3 as "Anzahl Autos im Haushalt",
hhgr06 as "Personen unter 6 Jahren",
hhgr14 as "Personen unter 14 Jahren",
hhgr18 as "Personen unter 18 Jahren",
anzerw as "Personen über 18 Jahren",
hp_sex as "Geschlecht",
hp_alter as "Alter",
hp_altg1 as "Altergruppe (Variante 1)",
hp_altg2 as "Altersgruppe (Variante 2)",
hp_altg3 as "Altersgruppe (Variante 3)",
hp_besch as "Tätigkeit und Arbeitszeit",
hp_pkwfs as "Pkw-Führerschein",
pergrup as "Verhaltenshomogene Personengruppe (9 Gruppen)",
pergrup1 as "Verhaltenshomogene Personengruppe (12 Gruppen)",
lebensph as "Lebensphase",
gesein as "Gesundheitliche Einschränkungen",
bland as "Bundesland",
westost as "West-Ost-Kennung",
polgk as "politische Gemeindegrößenklasse",
rtyp as "BBSR Regionsgrundtyp",
rtypd7 as "BBSR differenzierter Regionstyp",
ktyp as "BBSR Kreistyp",
ktyp_zsg as "BBR zusammengefasster Kreistyp",
sgtyp as "BBSR Stadt- und Gemeindetyp (4er)",
sgtypd as "BBSR differenzierter Stadt- und Gemeindetyp (7er)",
psu_nr as "laufende Nummer"
from mid2008.journeys;
